# Generated by Django 6.0.6 on 2026-06-20 17:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('identificacion', models.CharField(db_index=True, help_text='Cédula o RUC del cliente. Ej: 0903369387 / 0992988061001', max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('linea_numero', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado_linea', models.CharField(choices=[('NO_INSTALADO', 'No instalado'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('CANCELADO', 'Cancelado')], default='NO_INSTALADO', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('saldo_vencido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='core.cliente')),
            ],
            options={
                'ordering': ['cliente_id', 'linea_numero'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'linea_numero'), name='unique_linea_por_cliente')],
            },
        ),
    ]
